### ISSUE TITLE
[Design]: Number of rows to show in tables

### ISSUE THREAD

**Issue by Applefincher** [LamplightCRM/feedback#181]
### Does this relate to any of our high-level objectives?

- [ ] Continuity: is was hard for an existing user to figure this out...
- [ ] Accessible: this aspect was inaccessible or hard to use
- [ ] Works on all devices: this could be improved on a particular device

### Which of DUAPER does this relate to?

- [x] Discoverable - you can't find the thing you're looking for / expecting
- [x] Understandable - this doesn't make sense in this context
- [ ] Affordances - I didn't realise it's a control I could interact with
- [ ] Predictable - I was surprised not in a good way
- [x] Efficient - too many clicks or other interactions
- [ ] Responsive - there was no feedback about what's going on

### Please provide more details

Its very tedious to have to always extend the number of rows this every time I open a table.  Can it save my preference for number of rows somehow - or have a setting for it somewhere?
or make the default 25 or more?
It affects most tables, but thinking of Relationships tab and especially editing Attendance tables within a work record (viewing seems to show all as default fine)

**Comment by beatricejmurphy** [comment]
I think this issue and #102 are one and the same

**Comment by ClaireLMee** [comment]
I was also going to flag this for work records.  I tried setting attendance (tab 2) show records to the to 20 rather than the default 5 and I couldn't get it to save. Not sure if I would have to set this in every recurring record or if there is a template setting to default 20 people/lines for them all.

Also, I tried to change the order of the columns in attendance (tab 2) of a work records because the columns I needed did not show without scrolling and the names to do freeze so its hard to know who you are commenting about.  I could not get the new column order to save and was wondering if I could default this either in each recurring record or as a template default.

**Comment by mattparker** [comment]
Whatever global settings for 'number of rows' should be working on all 'view' type tables.

The attendance table won't be just yet, I don't think, or saved table layouts - still to do.

**Comment by mattparker** [comment]
also #179 relates to this

**Comment by beatricejmurphy** [comment]
Hi @mattparker 
Taking a look around at activity tables (those that show when you view records via Activity and activity tabs when viewing profiles) and those seem to now be displaying expected number of rows. Something curious though, we have ours set to show 25 rows by default - it is showing those 25 rows but the Number of rows to show box displays another number:

![Image](https://github.com/user-attachments/assets/28e79903-7cd3-401d-bd8c-d4b67eb66e7f) which may cause a little confusion ;)

**Comment by beatricejmurphy** [comment]
Oh spoke too soon, when trying to expand a table of profiles to see all 266 of them (rather than 25), you select all in the Number rows to show dropdown, the page blinks but then does not show you all rows, only the 25 you were just looking at a moment ago

**Comment by mattparker** [comment]
25 is because of a mismatch between 20 in the tables and 25 in global settings (and previous option).

Fix for this and all tonight.

**Comment by mattparker** [comment]
Update 20/2/2025 should resolve this

**Comment by beatricejmurphy** [comment]
Morning @mattparker Sorry to be the bearer of bad news but the Number of rows to show all option is still not showing all records. For example, I have a table that contains 6984 records, when you ask the table to be expanded to show all, it only shows me 100 rows not all. I know I am asking a lot from this specific example but we use the Number of rows to show All option A LOT here, especially at reporting time
