### ISSUE TITLE
[Bug]: save settings button in diary does not save settings

### ISSUE THREAD

**Issue by RubiesCharity** [LamplightCRM/feedback#193]
### What doesn't work?

I want my diary to always be in WORK WEEK VIEW and for TEAM not just ME - I have to set this every time I log in and every time I return to diary - even though I've clicked the save settings button. Please help!

### What did you see instead? Did you get a 'Problem saving' message? A 500 error (check Inspector)? Or something else?

None

### Can you reliably make the error happen repeatedly?

- [x] Yes, every time I try
- [ ] Yes, most times I try
- [ ] No it seems random

**Comment by mattparker** [comment]
Hi @RubiesCharity sorry about this - saving settings should now be working for all settings.

**Comment by RubiesCharity** [comment]
It still doesn't work for me - in diary view if I choose WORK WEEK and TEAM as the options, then click save settings -  when I log out and back in again it has defaulted back to WEEK and JUST ME
