### ISSUE TITLE
[Bug]: Diary - No entries in the diary

### ISSUE THREAD

**Issue by AimeeHuntSPN** [LamplightCRM/feedback#27]
### Do we know who you are?

Smart Play Network

### What doesn't work?

Comparing the old Lamplight diary to the new, none of the entries are shown in the new.  Wondering if there is a coding issue?

### What did you see instead? Did you get a 'Problem saving' message? A 500 error (check Inspector)? Or something else?

None

### Can you reliably make the error happen repeatedly?

- [ ] Yes, every time I try
- [ ] Yes, most times I try
- [ ] No it seems random

**Comment by mattparker** [comment]
@AimeeHuntSPN I believe this should be working for you now? I'm going to close this but you should be able to reopen it if it's on-going.

**Comment by AimeeHuntSPN** [comment]
I'm afraid it's just checked and it's still an issue.  I have re-opened it.  If you need to discuss this more happy to do so.

**Comment by AimeeHuntSPN** [comment]
I'm afraid this is not working still.  I can't re-open the issue, please could you re-open it for me?  Happy to discuss or provide more details if needed.

Thanks,

Aimee


Aimee Hunt

Operations Manager, Strategic | Smart Play Network


Working days: Tuesday, Wednesday and Thursday

________________________________
