### ISSUE TITLE
[Bug]: Downloads to csv - some fields are showing as numbers rather than words or categories

### ISSUE THREAD

**Issue by Angela12VA** [LamplightCRM/feedback#300]
### Do we know who you are?

AH from VA

### What doesn't work?

When downloading attendance lists from group events to a csv, the Attendance Type and the Attendance Role field are showing as numbers rather than the words Attended/DNA/Declined etc. or Saff/Volunteer/Member.  

### What did you see instead? Did you get a 'Problem saving' message? A 500 error (check Inspector)? Or something else?

None

### Can you reliably make the error happen repeatedly?

- [x] Yes, every time I try
- [ ] Yes, most times I try
- [ ] No it seems random

### Please paste any error messages from the console that appear when this happens

N/A

[Attendance list for an activity.csv](https://github.com/user-attachments/files/18981580/Attendance.list.for.an.activity.csv)

**Comment by mattparker** [comment]
Hi @Angela12VA 

Thanks for this. This had been raised previously and I thought was resolved (#150 ). When I download from my test systems I definitely get the text.

Could you double check you've got the latest version by holding `Ctrl` key and pressing `F5` to reload the page - that should make sure you've got the most recent. And then try downloading again.

If you're still seeing this, could you outline the steps you're taking to get the download please (e.g. do you start from the diary or in a profile)?

Thanks

**Comment by Angela12VA** [comment]
Hi Matt

I’ve just logged in again using the new.lamplight.online link.  Did a Ctrl F5 too.  It’s still happening.

My route to the download was:

  *   Activity
  *   View work records
  *   Selected record using the little icon in LHS column and then Edit
  *   Selected the Attendance tab.
  *   Scrolled to the bottom and used the Download icon at the bottom of the attendance table.

The actual work record ID is 7347, if that’s of any use.  However, I have tried it on various different work records with the same result.

Angela

Angela Hook
Befriending Lead

My Working Hours: Monday-Wednesday, 09:00 – 13:00

***@***.***

**Comment by mattparker** [comment]
Thanks @Angela12VA that's helpful. It's definitely working OK if you view the saved record and download the table there. I'll update for this too.

**Comment by mattparker** [comment]
Last update does resolve this, although you may need another Ctrl-F5 to get the latest (this won't be necessary once we move out of testing incidentally)
