### ISSUE TITLE
[Bug]: Work record doesn't save

### ISSUE THREAD

**Issue by KarenMA410** [LamplightCRM/feedback#514]
### What doesn't work?

If you add a work record, activity, it does not save. Have tested.
It will save if you use a template.
If you are on the  diary and drag to open a box then populate the  data it doesn't matter if you save at the top or the bottom it doesn't save the entry.  Possibly related to custom change to remove drag bar?

### What did you see instead? Did you get a 'Problem saving' message? A 500 error (check Inspector)? Or something else?

None

### Can you reliably make the error happen repeatedly?

- [x] Yes, every time I try
- [ ] Yes, most times I try
- [ ] No it seems random

**Comment by mattparker** [comment]
Hi @KarenMA410 there was an issue when a work record would fail to save if you had another 'add work record' screen open in another tab or window at the same time. The latest update resolves this. 

I'm not sure if this is the problem you experienced here - would you be able to try again now and check if you're still seeing this? I'm not seeing this behaviour on other systems.

Thanks

**Comment by KarenMA410** [comment]
Not fixed. On no occasion did I have another work record screen open. I have tested this morning and it remains the same,  it does not save.

Probably not seeing this on other systems because as I say we had the drag handles removed, custom change, and this could be the root cause.

**Comment by mattparker** [comment]
I wonder if this was the issue with the required fields not warning that they needed to be completed? The update last night should fix this so that you get the warning before it tries to save, as with other required fields.

**Comment by KarenMA410** [comment]
All required fields completed so doubt if this will resolve the issue but am opening another issue related to that.

**Comment by KarenMA410** [comment]
Still not working.

Work record is being saved but not in diary.

![Image](https://github.com/user-attachments/assets/c187d23d-2c55-4f70-8c7b-b6a87dcb3cc4)

![Image](https://github.com/user-attachments/assets/e0b3e02e-f2ea-46dd-9935-7ae7bf69f978)

![Image](https://github.com/user-attachments/assets/1874c22a-6897-43b6-84cc-9dd17e273313)

**Comment by rbowsley** [comment]
We've turned off autosave (couldn't see any autosaves from affected records) and turned on the audit module temporarily. Will review with @KarenMA410 next week.
